// `scalafixConfigured*` (from ScalafixConfigPlugin) and `scalafixConfig` (from sbt-scalafix)
// are auto-imported by enabling the plugins below — no explicit imports needed.

lazy val root = project
  .in(file("."))
  .enablePlugins(ScalafixConfigPlugin)
  .settings(
    scalaVersion := "2.12.21",
    // Compile: a strict rule set with a configured rule block.
    Compile / scalafixConfiguredRules := Seq("DisableSyntax", "OrganizeImports"),
    Compile / scalafixConfiguredSettings := Map(
      "DisableSyntax" -> Map("noFinalize" -> true),
      "OrganizeImports" -> Map(
        "targetDialect" -> "Scala3",
        "groups" -> Seq("re:javax?\\.", "scala", "*"),
      ),
    ),
    // Test: derived from Compile — drop OrganizeImports, but keep the rest (including
    // DisableSyntax's settings block). This is the idiomatic "Test = Compile minus a rule"
    // pattern, since the keys are plain settings.
    Test / scalafixConfiguredRules :=
      (Compile / scalafixConfiguredRules).value.filterNot(_ == "OrganizeImports"),
    Test / scalafixConfiguredSettings :=
      (Compile / scalafixConfiguredSettings).value - "OrganizeImports",
  )

// A project that enables the plugin but declares NO rules. Its scalafixConfig must be left
// untouched (the plugin only wires it when a configuration declares rules).
lazy val noRules = project
  .in(file("no-rules"))
  .enablePlugins(ScalafixConfigPlugin)
  .settings(scalaVersion := "2.12.21")

// --- assertions, run from the `test` script ---

val checkFilesExist = taskKey[Unit]("Both generated config files exist")
checkFilesExist := {
  val main = (Compile / scalafixConfiguredFile).value
  val test = (Test / scalafixConfiguredFile).value
  assert(main.getName == ".scalafix.conf", s"unexpected Compile file name: ${main.getName}")
  assert(test.getName == ".scalafix.test.conf", s"unexpected Test file name: ${test.getName}")
  assert(main.isFile, s"$main was not generated")
  assert(test.isFile, s"$test was not generated")
}

val checkContents = taskKey[Unit]("Generated files have the expected banner + differing rules")
checkContents := {
  val mainTxt = IO.read((Compile / scalafixConfiguredFile).value)
  val testTxt = IO.read((Test / scalafixConfiguredFile).value)

  Seq(mainTxt, testTxt).foreach { txt =>
    assert(
      txt.contains("automatically generated by the sbt-scalafix-config plugin"),
      s"missing banner header in:\n$txt",
    )
  }

  // Compile config has OrganizeImports (with its block); Test does not.
  assert(mainTxt.contains("OrganizeImports"), s"Compile config missing OrganizeImports:\n$mainTxt")
  assert(mainTxt.contains("targetDialect"), s"Compile config missing OrganizeImports block:\n$mainTxt")
  assert(!testTxt.contains("OrganizeImports"), s"Test config should be relaxed (no OrganizeImports):\n$testTxt")

  // Test inherited the rest from Compile: DisableSyntax and its noFinalize settings block
  // survive even though OrganizeImports was dropped.
  assert(testTxt.contains("DisableSyntax"), s"Test config missing inherited DisableSyntax:\n$testTxt")
  assert(testTxt.contains("noFinalize"), s"Test config missing inherited DisableSyntax block:\n$testTxt")
}

val checkScalafixWired = taskKey[Unit]("sbt-scalafix's scalafixConfig points at our generated files per config")
checkScalafixWired := {
  val main = (Compile / scalafixConfig).value
  val test = (Test / scalafixConfig).value
  assert(
    main.contains((Compile / scalafixConfiguredFile).value),
    s"Compile / scalafixConfig not wired: $main",
  )
  assert(
    test.contains((Test / scalafixConfiguredFile).value),
    s"Test / scalafixConfig not wired: $test",
  )
}

val checkNoRulesNotWired =
  taskKey[Unit]("A config with no rules leaves scalafixConfig untouched (default None)")
checkNoRulesNotWired := {
  val main = (noRules / Compile / scalafixConfig).value
  val test = (noRules / Test / scalafixConfig).value
  assert(main.isEmpty, s"noRules Compile / scalafixConfig should be None, was: $main")
  assert(test.isEmpty, s"noRules Test / scalafixConfig should be None, was: $test")
}

val mutateMainConfig = taskKey[Unit]("Corrupt the generated Compile config to force a staleness failure")
mutateMainConfig := {
  val f = (Compile / scalafixConfiguredFile).value
  IO.write(f, IO.read(f) + "\n# tampered\n")
}

val mutateTestConfig = taskKey[Unit]("Corrupt the generated Test config to force a staleness failure")
mutateTestConfig := {
  val f = (Test / scalafixConfiguredFile).value
  IO.write(f, IO.read(f) + "\n# tampered\n")
}
